name: test-environment
channels:
- conda-forge
- defaults
dependencies:
  - python=${PYTHON}
  - pytest>=3.2.0
  - pytest-cov
  - coveralls
  - networkx
  - numpy
  - osmnx
  - pytables
  - pandas
  - scikit-learn